### PR TITLE
add UniversalJS logo

### PR DESCRIPTION
**Pull request by WebReflection**
the author of [the famous post](https://twitter.com/mjackson/status/607951851091169280) agreed [this logo might be the one](https://twitter.com/mjackson/status/612648222406750208).

I hope it will make it into this repository.

Thank You

### CODE REVIEW

**Comment by voodootikigod** [comment]
Maybe I don't understand the point of this, can you provide some context? How is this any more/less universal than the already existing JS logo?

**Comment by WebReflection** [comment]
It's explicitly for a "Universal JS", as opposite of "Isomorphic JS", intended code/library/project while the JS one is used generically for anything JS related, not something that would necessarily run, or that has been developed to run, universally.

Does this explain any better the intent?

**Comment by WebReflection** [comment]
just to quote the end of the original post:

> So let’s give our JavaScript code a name that people can understand; a name that indicates what it actually does instead of introducing words into the common vernacular that clearly don’t belong there; a name that teaches people that it runs not only on servers and browsers, but on native devices and embedded architectures as well.
> 
> Let’s call it Universal JavaScript.

So while the JS logo keeps being the reference, Universal JS logo would be the explicit reference to code that runs in embedded, client, server engines.

Hope this explains better the intent

**Comment by WebReflection** [comment]
Thank you!

**Pull request merged**
